### ISSUE TITLE
GET​/api​/variant​/{variant_id}​/{caller}​/{api_key} / 0.6.2 not shown using google Chrome

### ISSUE THREAD

**Issue by JiMouse** [beboche/MobiDetails#19]
Hi,
I'm not sure how I did wrong but I'm not seeing your new feature using google chrome (Version 90.0.4430.212 (Build officiel) (64 bits) on my windows 10 but it is working properly with Internet Explorer. No problem either with my Android.
I don't know if it is a bug on my side...
There problem seems to be that the version "0.5.2" is rendered and no the "0.6.2"
![Image1](https://user-images.githubusercontent.com/33331141/119981964-8a4e2280-bfbe-11eb-8af6-50544f797b47.png)

Thank you for this amasing tool,
Jean-Marie (Nancy, France)

**Comment by beboche** [comment]
Hi @JiMouse,

my guess is that you just need to empty your browser's cache.
Let me know if this work!
Best
david

**Comment by JiMouse** [comment]
Hi David,
Thanks, it works ! Sorrry for this rookie mistake,
Bonne journée,

JM

**Comment by beboche** [comment]
you're welcome
