### ISSUE TITLE
IGV.js bug : Translation

### ISSUE THREAD

**Issue by Char-Al** [beboche/MobiDetails#30]
# Bug with IGV.js

A bug appear when you activate the translation sequence on IGV.js.

When you zoom out and zoom in (tested on chrome and firefox on macos) the translation sequence does not shift properly.

Furthermore the pdf export is completely shift...

![ezgif-3-010d403961](https://user-images.githubusercontent.com/10559615/190365459-06b60b24-e674-40fa-a870-42638993bb16.gif)

**Comment by beboche** [comment]
As you mentioned this is an igv.js bug - current version in MD is 2.12.2

The bug seems to have been corrected in 2.12.14: https://github.com/igvteam/igv.js/issues/1493 ; https://github.com/igvteam/igv.js/releases

I'll test a more recent version.
