### ISSUE TITLE
Improve the `/api/variant/create_g` API method, add support for hg19.

### ISSUE THREAD

**Issue by ifokkema** [beboche/MobiDetails#4]
The `/api/variant/create_g` API method currently allows for creating variants in MobiDetails based on hg38. LOVD [recently added a link to MD](/LOVDnl/LOVD3/pull/465), using the `/api/variant/create` method because having hg38 data couldn't be guaranteed. The first issues, however, have already shown up where LOVD uses older transcripts that are not supported. Being able to submit the variant on either hg19 or hg38 would fix that problem and would allow LOVD to submit any variant.

**Comment by beboche** [comment]
Change applied and pushed. You can make some tests via the swagger:
https://mobidetails.iurc.montp.inserm.fr/MDAPI/
