### ISSUE TITLE
Use the HGNC ID to submit data to LOVD, not the gene symbol

### ISSUE THREAD

**Issue by ifokkema** [beboche/MobiDetails#5]
When using the LOVD submission API to send classifications to LOVD, it's best to avoid using gene symbols because LOVD can be using older gene symbols (which is an issue they need to solve, obviously). Until then, LOVD is [currently working on processing HGNC IDs](/LOVDnl/LOVD3/issues/466) in their submission API. When that's done, it would be good to start using that feature.

Depends: LOVDnl/LOVD3/issues/466.

**Comment by beboche** [comment]
done
