### ISSUE TITLE
GnomAD

### ISSUE THREAD

**Issue by Char-Al** [beboche/MobiDetails#55]
It seems that currently there is an error on GnomAD non-cancer fields.

I think that for the exome _non-cancer_ the value that appears is only the first and not the global one, and that no value appears for the genome _non-cancer.

Example:
https://mobidetails.iurc.montp.inserm.fr/MD/api/variant/373349/browser/
<img width="1480" alt="image" src="https://github.com/beboche/MobiDetails/assets/10559615/fa6fd800-ded1-451c-825f-4b2f7e14df09">
Values expected : 
exome _non-cancer_ : 0.4693   (0.5368 => only South Asian)
genome _non-cancer_ : 0.4163

<img width="1497" alt="image" src="https://github.com/beboche/MobiDetails/assets/10559615/5fe69edd-d6cc-475e-8953-4cbb71a70b59">
Values expected : 
exome _non-cancer_ : 0.7166  (0.9182 => only AFR exome)
genome _non-cancer_ : 0.7559

**Comment by beboche** [comment]
Hi @Char-Al ,

concerning your first question, exome non-cancer, it is mentioned in the description field that the reported value is the MAX MAF for this dataset.

You are right for the second question, my data source for gnomAD211 geneome non-cancer looke always empty.

I'll remove this field asap waiting for a long-term fix.

**Comment by beboche** [comment]
Do not hesitate to reopen if the long-term fix does not show up ;-)
