### ISSUE TITLE
Don't drop support for an entire gene if one transcript fails

### ISSUE THREAD

**Issue by ifokkema** [beboche/MobiDetails#6]
I know this is on your radar already, but just to have it registered here; LOVD now uses the `create_g` method and sends the genomic variant to MD, including an HGNC ID of the relevant gene. This fails for genes where one of the transcripts isn't fully supported by VariantValidator.

For instance, the IVD gene is supported when using the `create` method and sending [`NM_002225.3:c.157C>T`](https://mobidetails.iurc.montp.inserm.fr/MD/variant/14775). Is is not supported when using the `create_g` method and sending `NC_000015.9:g.40700194G>A` with HGNC ID 6186. MD's reply is:

```
mobidetails_error: The gene 6186 is currently not available for variant annotation in MobiDetails
```

However, since the problem is caused by NM_002225.4 and not NM_002225.3, the variant can actually be annotated and processed. My suggestion would be to drop the transcripts not working, and use the one(s) that are.

**Comment by beboche** [comment]
First elements of answer:

- with the new API you are no longer able to add variants using the `create_g` method for the _IVD_ gene, either using NM_002225.3 or NM_002225.4
- the API returns the same object in both cases: 
```
{  
 "mobidetails_error": "The gene corresponding to NM_002225 is not yet available for variant annotation in MobiDetails"
}
```

- second the already annotated variants may be wrong, e.g. [NM_002225.3:c.158G>C](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_002225.3%3Ac.158G%3EC/all?content-type=application%2Fjson) is different from [NM_002225.4:c.158G>C](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_002225.4%3Ac.158G%3EC/all?content-type=application%2Fjson). Try it with VariantValidator: You will get an error for [NM_002225.4:c.158G>C](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_002225.4%3Ac.158G%3EC/all?content-type=application%2Fjson): Variant reference (G) does not agree with reference sequence (T)

Then several actions to be taken

- [ ] check the already annotated variants and remove wrong ones 

- [ ] disable the ability to submit a different accession number than the current one in MD => less flexibility but less errors

- [ ] check the feasability to revert NM_002225 from 4 to 3 ane reenable IVD

**Comment by ifokkema** [comment]
Yes, indeed NM_002225.3 is very different from NM_002225.4. I always test with the _IVD_ gene as it always breaks things somewhere :sweat_smile:! Switching transcript versions doesn't work for this gene, and it reminds us not to do that (although it often just works for normal genes).

I verified the current 6 _IVD_ variants in MD, and they're correct. Perhaps because of you correcting them and/or removing incorrect variants. When listing all _IVD_ variants in MD, it would actually be a good idea to add the version there, too.

> disable the ability to submit a different accession number than the current one in MD => less flexibility but less errors

If this applies only to the `create` method, that would be OK. For the `create_g` method, it would be good if MD picks a well-working transcript from VV's output and just focus on that, even though there might be transcripts in there that don't work well in both genome builds.

**Comment by beboche** [comment]
> I verified the current 6 _IVD_ variants in MD, and they're correct. Perhaps because of you correcting them and/or removing incorrect variants. When listing all _IVD_ variants in MD, it would actually be a good idea to add the version there, too.
> 
yes, added in the todo list above
> > disable the ability to submit a different accession number than the current one in MD => less flexibility but less errors
> 
> If this applies only to the `create` method, that would be OK. For the `create_g` method, it would be good if MD picks a well-working transcript from VV's output and just focus on that, even though there might be transcripts in there that don't work well in both genome builds.
>
Yes it's only for the `create` method. The `create_g` works ~ as in your description. Anyway MD's RefSeq is synchronised with VV's (with a delay).

**Comment by beboche** [comment]
Issue closed although the subject is sensitive and requires regular updates.
